public enum RequestType {
    GET_DATABASES, CREATE_DATABASE, DELETE_DATABASE, CREATE_TABLE, GET_TABLES, DELETE_TABLE, ADD_FOREIGN_KEY, GET_TABLE_FIELDS, CREATE_INDEX, INSERT_DATA, DELETE_DATA, UPDATE_DATA, SELECT, SELECT_DATE, GET_REF_TABLES, EXT_SORT_JOIN, LOGIN, REGISTER, CHANGE_PASSWORD;
}
